const ADD_BLUETOOTH = "ADD_BLUETOOTH";
const LOAD_BLUETOOTH = "LOAD_BLUETOOTH";  
const REMOVE_BLUETOOTH = "REMOVE_BLUETOOTH"; 
const CHECKED ="CHECKED";
const UNCHECKED = "UNCHECKED";

const STATUS_SET = "STATUS_SET";
const STATUS_UNSET = "STATUS_UNSET";
const CONTENT_LOAD_INPROGRESS = "CONTENT_LOAD_INPROGRESS";
const CONTENT_LOAD_NOTINPROGRESS = "CONTENT_LOAD_NOTINPROGRESS";

export { ADD_BLUETOOTH, LOAD_BLUETOOTH, REMOVE_BLUETOOTH, CHECKED, UNCHECKED, STATUS_SET, STATUS_UNSET, CONTENT_LOAD_INPROGRESS, CONTENT_LOAD_NOTINPROGRESS };

