const ADD_BLUETOOTH = "ADD_BLUETOOTH";
const LOAD_BLUETOOTH = "LOAD_BLUETOOTH";  
const REMOVE_BLUETOOTH = "REMOVE_BLUETOOTH"; 
const CHECKED ="CHECKED";
const UNCHECKED = "UNCHECKED";

export { ADD_BLUETOOTH, LOAD_BLUETOOTH, REMOVE_BLUETOOTH, CHECKED, UNCHECKED };

