const ADD_BLUETOOTH = "ADD_BLUETOOTH";
const LOAD_BLUETOOTH = "LOAD_BLUETOOTH";  
const REMOVE_BLUETOOTH = "REMOVE_BLUETOOTH"; 
const CHECKED ="CHECKED";
const UNCHECKED = "UNCHECKED";

const STATUS_SET = "STATUS_SET";
const STATUS_UNSET = "STATUS_UNSET";
const CONTENT_LOAD_INPROGRESS = "CONTENT_LOAD_INPROGRESS";
const CONTENT_LOAD_NOTINPROGRESS = "CONTENT_LOAD_NOTINPROGRESS";

const YTVIDEO_PLAY = "YTVIDEO_PLAY";
const YTVIDEO_PAUSE = "YTVIDEO_PAUSE";
const YTVIDEO_FORWARD = "YTVIDEO_FORWARD";
const YTVIDEO_VOL_INCR = "YTVIDEO_VOL_INCR";
const YTVIDEO_VOL_DECR = "YTVIDEO_VOL_DECR";

export { ADD_BLUETOOTH, LOAD_BLUETOOTH, REMOVE_BLUETOOTH, CHECKED, UNCHECKED, STATUS_SET, STATUS_UNSET, CONTENT_LOAD_INPROGRESS, CONTENT_LOAD_NOTINPROGRESS 
, YTVIDEO_PLAY, YTVIDEO_PAUSE, YTVIDEO_FORWARD,YTVIDEO_VOL_DECR, YTVIDEO_VOL_INCR};

